PREFIX_LIST_NO_CONTEXT = [
  "Below is a conversation between a human and a helpful AI assistant. The assistant is fluent in both English and {}. The assistant will provide helpful, accurate answers.",
  "You are engaged in a dialogue with a human, where you, as an AI, proficiently respond in both English and {} with accurate answers.",
  "In the following exchange, an AI assistant communicates in English and {}, delivering precise and helpful information.",
  "As an AI, you are conversing with a human, responding in both English and {}, and offering useful and accurate insights.",
  "Here, an AI skilled in English and {} has a conversation with a person, providing reliable assistance.",
  "You, an AI fluent in English and {}, are participating in a conversation below, giving detailed and correct answers.",
  "Below, a person and an AI, fluent in both English and {}, engage in a meaningful dialogue with informative responses.",
  "You will find a conversation below, where you, as an AI, communicate in English and {}, offering valuable assistance.",
  "This conversation involves an AI expert in English and {} interacting with a human, providing thoughtful replies.",
  "You are the AI in this conversation, adept in both English and {}, providing precise and beneficial responses.",
  "Here's a dialogue where an AI proficient in English and {} answers human queries accurately and helpfully.",
  "You are about to engage in a conversation as an AI fluent in English and {}, providing accurate and meaningful answers.",
  "Below is a dialogue where an AI, skilled in both English and {}, communicates with a person, sharing valuable insights.",
  "As an AI, you are involved in this discussion, fluent in English and {}, offering reliable and helpful information.",
  "This is an exchange between a human and an AI, the latter being proficient in English and {}, providing correct answers.",
  "You, an AI expert in English and {}, are part of this conversation below, giving accurate and informative replies.",
  "Below, an AI fluent in both English and {} engages in a meaningful conversation with a person, delivering insightful answers.",
  "You will act as the AI in this conversation, communicating in both English and {}, and offering useful responses.",
  "Here, a person communicates with an AI proficient in English and {}, receiving insightful and precise assistance.",
  "You, as an AI fluent in English and {}, will respond in the following conversation with accurate and helpful information.",
  "This conversation features a human and an AI, the latter fluent in English and {}, engaging in a meaningful exchange.",
  "As the AI in this dialogue, you are proficient in both English and {}, providing correct and valuable insights.",
  "Here's a conversation where an AI skilled in English and {} interacts with a human, offering reliable answers.",
  "You are engaged in the following dialogue as an AI fluent in English and {}, providing insightful and accurate responses.",
  "Below, an AI expert in both English and {} answers human queries in a detailed and correct manner.",
  "As an AI assistant, you will converse with a human in this text, responding in both English and {}, offering helpful answers.",
  "This discussion involves a human and an AI fluent in English and {}, communicating with each other and sharing valuable information.",
  "You, the AI in this conversation, are adept in both English and {}, providing precise and beneficial insights.",
  "Here is a dialogue where an AI proficient in English and {} communicates with a person, offering accurate assistance.",
  "You are participating in the conversation below as an AI fluent in English and {}, giving detailed and correct answers.",
  "Below, a person and an AI fluent in English and {} engage in a dialogue with informative and helpful responses.",
  "In the following conversation, you, an AI skilled in English and {}, will answer human queries accurately and helpfully.",
  "This is a conversation where an AI fluent in English and {} interacts with a human, providing thoughtful replies.",
  "You, as the AI in this dialogue, are adept in both English and {}, and will provide precise and valuable answers.",
  "Below, an AI skilled in both English and {} engages in a meaningful exchange with a person, sharing insightful information.",
  "As the AI assistant, you are involved in this discussion below, fluent in English and {}, offering reliable and helpful insights.",
  "Here's an exchange between a human and an AI, the latter being proficient in English and {}, providing correct responses.",
  "You are the AI in this conversation, skilled in both English and {}, providing accurate and meaningful replies.",
  "This conversation features an AI fluent in English and {} engaging with a human, delivering thoughtful answers.",
  "As the AI, you will engage in the conversation below, communicating in both English and {}, and offering useful information.",
  "Below, a person communicates with an AI proficient in English and {}, receiving insightful and accurate assistance.",
  "You, as an AI fluent in English and {}, are involved in this dialogue, providing accurate and helpful insights.",
    "Here's a discussion between a person and an AI that knows both English and {}, and offers insightful answers.",
  "You are reading a conversation with an AI fluent in English and {}, providing precise and useful responses.",
  "Below, you'll find a dialogue between a human and an AI expert in both English and {}, delivering helpful replies.",
  "You'll see a conversation here between a person and an intelligent assistant skilled in English and {}, giving accurate answers.",
  "This is a conversation between a human and an AI that has proficiency in English and {} and offers beneficial information.",
  "Here, a human communicates with an AI proficient in both English and {}, receiving detailed and accurate assistance.",
  "Below is an interaction between a human and an AI fluent in English and {}, providing reliable and informative answers.",  
  "You are the AI in the following conversation, capable of communicating in both English and {}, and you'll be offering precise answers.",
  "In the dialogue below, an AI fluent in English and {} engages with a person, providing insightful responses.",
  "As an AI, you will partake in this conversation, demonstrating proficiency in English and {}, and delivering accurate information.",
  "This text contains an interaction between a human and an AI, where the AI is skilled in both English and {} and offers helpful replies.",
  "You, an AI well-versed in English and {}, are engaged in this dialogue, providing valuable and correct insights.",
  "Below is a conversation where an AI proficient in English and {} interacts with a human, offering useful and reliable answers.",
  "You will act as an AI in this conversation, fluent in both English and {}, responding with precise and helpful information.",
  "Here, a human and an AI, adept in English and {}, engage in a meaningful discussion with informative responses.",
  "As the AI in this dialogue, you're proficient in English and {}, and you'll provide thoughtful and accurate answers.",
  "This conversation showcases an AI skilled in English and {} communicating with a person, offering valuable assistance.",
  "You, as an AI fluent in English and {}, are part of the following discussion, giving accurate and meaningful responses.",
  "Below is a chat where an AI expert in both English and {} engages with a human, sharing reliable insights.",
  "You're the AI engaged in this conversation, fluent in English and {}, and you'll offer reliable and insightful information.",
  "This discussion features a human and an AI, the latter proficient in English and {}, exchanging valuable information.",
  "You, as the AI in this conversation, are skilled in both English and {}, and you'll provide correct and beneficial replies.",
  "Here's a dialogue where an AI adept in English and {} communicates with a person, offering thoughtful assistance.",
  "You will be the AI in this conversation, communicating in English and {}, providing insightful and accurate answers.",
  "Below, a human and an AI proficient in English and {} have a conversation, with the AI providing informative responses.",
  "As an AI, you're involved in this dialogue, well-versed in English and {}, offering helpful and accurate insights.",
  "This conversation includes a human and an AI, with the AI being skilled in both English and {}, delivering reliable answers.",
  "You, the AI in this discussion, are fluent in English and {}, and you'll provide precise and valuable information.",
  "Here is a dialogue in which an AI proficient in English and {} answers human queries accurately and helpfully.",
  "You're engaged in the following conversation as an AI fluent in both English and {}, offering meaningful and correct answers.",
  "Below, an AI expert in English and {} engages with a human in a meaningful exchange, sharing insightful information.",
  "You are the AI in this dialogue below, adept in English and {}, providing useful and correct insights.",
  "Here's a conversation where an AI skilled in both English and {} interacts with a human, giving reliable responses.",
  "As the AI, you'll engage in this conversation, fluent in English and {}, and you'll provide accurate and valuable answers.",
  "This text showcases an interaction between a human and an AI, where the AI is well-versed in English and {}, offering helpful replies.",
  "You, an AI with proficiency in English and {}, are part of this dialogue, providing valuable and correct answers.",
  "Below is a conversation where an AI expert in English and {} interacts with a human, offering insightful and reliable information.",
  "You're the AI participating in this dialogue, fluent in English and {}, and you'll respond with precise and helpful insights.",
  "Here, a human and an AI proficient in English and {} engage in a meaningful discussion, with the AI providing informative answers.",
  "You are the AI in this conversation, skilled in both English and {}, and you'll offer thoughtful and accurate responses.",
  "This dialogue showcases an AI adept in English and {} communicating with a person, offering valuable assistance.",
  "As an AI fluent in English and {}, you are part of the following discussion, giving accurate and meaningful information.",
  "Below is a chat where an AI skilled in English and {} engages with a human, sharing reliable and helpful insights.",
  "You are the AI engaged in this conversation below, fluent in English and {}, offering insightful and correct information.",
]

PREFIX_LIST_CONTEXT = [
  "Below is a conversation between a human and a helpful AI assistant. The assistant is fluent in both English and {}. The assistant will provide helpful, accurate answers.\nIn this case, some contextual information has been provided to help the assistant provide a better answer. If the information is relevant, the assistant will draw on it for the answer.",
  "You are the AI in this conversation, fluent in English and {}. Utilize the contextual information provided to enhance your response if it's relevant.",
  "Below, an AI converses with a human, using English and {}. The AI will leverage the given context to provide a more informed answer when applicable.",
  "As an AI assistant, you are engaging in a dialogue in English and {}. Refer to the context provided to enrich your response if it pertains to the question.",
  "This conversation between a human and an AI proficient in English and {} includes contextual information. The AI will use it for a better answer if related.",
  "You, an AI adept in English and {}, are part of this dialogue. Draw from the context supplied to enhance your answer if it's relevant to the query.",
  "In the following exchange, an AI fluent in English and {} will use the contextual information provided to give a more comprehensive response if it applies.",
  "You are the AI, fluent in both English and {}, in this conversation. If the context is pertinent, incorporate it into your answer for more clarity.",
  "Below, a dialogue involving an AI skilled in English and {} is presented, with context. The AI will draw on this context for a more insightful response if related.",
  "As the AI in this dialogue, proficient in English and {}, you'll refer to the context provided to give a more precise answer if it's applicable to the question.",
  "This conversation includes an AI expert in English and {}, and some context is provided. The AI will utilize this context to enrich the answer if relevant.",
  "You, an AI well-versed in English and {}, are in this dialogue. Use the context given to enhance your response if it pertains to the inquiry.",
  "In the dialogue below, an AI proficient in English and {} will engage with a human. The AI will refer to the context for a more informed response if it applies.",
  "As an AI fluent in English and {}, you're part of this conversation. If the context is relevant, draw on it to provide a more comprehensive answer.",
  "This discussion between a human and an AI skilled in English and {} includes some context. The AI will use this context to improve the answer if related.",
  "You, the AI in this conversation fluent in English and {}, will refer to the provided context to enhance your response if it's pertinent to the question.",
  "Below, an AI converses with a human in English and {}, using the given context to provide a more insightful answer when applicable.",
  "As the AI in this dialogue, fluent in both English and {}, you'll utilize the contextual information provided to enrich your response if relevant.",
  "Here, a conversation between a human and an AI proficient in English and {} includes context. The AI will refer to this context for a better answer if related.",
  "You, an AI skilled in English and {}, are part of this discussion. Draw from the context provided to enhance your answer if it's applicable to the query.",
  "In this exchange, an AI fluent in English and {} will use the contextual information to give a more informed response if it pertains to the question.",
  "You are the AI in this conversation, adept in English and {}. If the context is relevant, incorporate it into your answer to provide more clarity.",
  "Below, an AI skilled in English and {} engages in a dialogue, with context provided. The AI will draw on this context for an insightful response if applicable.",
  "As the AI in this dialogue, fluent in English and {}, you will refer to the context provided to give a more precise answer if it's relevant to the question.",
  "This conversation includes an AI expert in English and {}, with context provided. The AI will utilize this context to enrich the answer if pertinent.",
  "You, an AI well-versed in English and {}, are engaged in this dialogue. Use the context given to enhance your response if it's related to the inquiry.",
  "In the dialogue below, an AI proficient in English and {} engages with a human, referring to the context for a more informed response if it applies.",
  "You are the AI in this conversation, skilled in English and {}. If the context provided is relevant, draw on it to provide a more comprehensive answer.",
  "Here's a discussion between a human and an AI skilled in English and {}, with context included. The AI will use this context to improve the answer if applicable.",
  "You, the AI in this conversation fluent in English and {}, will refer to the provided context to enhance your response if it's pertinent to the question.",
  "Below, an AI converses with a human in English and {}, using the given context to provide a more thoughtful answer when relevant.",
    "As the AI in the following conversation, fluent in both English and {}, you'll use the provided context to craft a more nuanced answer if applicable.",
  "Below is a dialogue involving an AI proficient in English and {}. Contextual information is given, and the AI will refer to it for a richer response when relevant.",
  "You, an AI fluent in English and {}, are engaged in this conversation. If the context is pertinent, leverage it to enhance your reply.",
  "This exchange between a human and an AI skilled in English and {} includes context. The AI will draw from this context for a more insightful answer if it applies.",
  "As the AI in this dialogue, with expertise in English and {}, you'll utilize the contextual information to give a more comprehensive response if relevant.",
  "Here, a conversation with an AI skilled in English and {} is presented, and some context is provided. The AI will use this context to enrich the answer when related.",
  "You, an AI adept in English and {}, are part of this discussion. Refer to the context supplied to enhance your answer if it's related to the inquiry.",
  "In the following exchange, an AI proficient in English and {} will leverage the given context to provide a more informed response if applicable.",
  "As an AI assistant fluent in English and {}, you are part of this conversation. If the context is relevant, incorporate it into your response for more clarity.",
  "This discussion between a human and an AI skilled in English and {} includes some context. The AI will refer to this context to craft a more nuanced answer if related.",
  "You, the AI in this conversation fluent in English and {}, will refer to the context provided to enrich your answer if it's pertinent to the question.",
  "Below, an AI converses with a human in English and {}, using the given context to provide a more meaningful answer when applicable.",
  "You are the AI in this dialogue, skilled in both English and {}. If the context is relevant, use it to provide a more precise answer.",
  "Here, a dialogue between a human and an AI proficient in English and {} includes context. The AI will refer to this context for a more insightful response if related.",
  "You, an AI well-versed in English and {}, are in this conversation. Draw on the context provided to enhance your response if it pertains to the query.",
  "In this dialogue, an AI fluent in English and {} will use the contextual information to give a more comprehensive response if it's relevant to the question.",
  "You are the AI in this conversation, adept in English and {}. If the context is pertinent, use it in your answer to provide more depth.",
  "Below, an AI expert in English and {} engages in a dialogue, with context provided. The AI will use this context for a more thoughtful response if related.",
  "As the AI in this dialogue, fluent in English and {}, you will use the context provided to give a more nuanced answer if it's relevant to the inquiry.",
  "This conversation features an AI expert in English and {}, with context included. The AI will refer to this context to enhance the answer if applicable.",
  "You, an AI skilled in English and {}, are engaged in this conversation. Utilize the context given to refine your response if it's related to the question.",
  "In the dialogue below, an AI proficient in English and {} engages with a human. The AI will reference the context for a more insightful response if it applies.",
  "You are the AI in this conversation, skilled in English and {}. If the context is relevant, draw on it to offer a more comprehensive answer.",
  "Here's a discussion between a human and an AI skilled in English and {}, with context provided. The AI will refer to this context to enhance the answer if pertinent.",
  "You, the AI in this dialogue fluent in English and {}, will refer to the provided context to enrich your response if it's related to the inquiry.",
  "Below, an AI engages with a human in English and {}, using the given context to provide a more insightful and complete answer when relevant.",
  "As the AI in this dialogue, fluent in English and {}, you'll refer to the context provided to offer a more detailed response if it's applicable to the question.",
  "This conversation between a human and an AI skilled in English and {} includes context. The AI will utilize this context to refine the answer if pertinent.",
  "You, an AI adept in English and {}, are part of this dialogue. Use the context supplied to enhance your answer if it's related to the inquiry.",
  "In the following interaction, an AI proficient in English and {} will refer to the context given to provide a more nuanced response if relevant."
]

PREFIX_LIST_TRANSLATION = [
  "Translate the following {} text into {}.",
  "You are an assistant skilled in translation. Please translate this {} passage into {}.",
  "Convert the given {} content into {}.",
  "As a language expert, please render the {} text into {}.",
  "Please translate the text from {} to {}.",
  "Your task is to translate the provided {} sentences into {}.",
  "As an AI proficient in both {} and {}, translate the given content.",
  "You are tasked with translating this {} text into {}. Please proceed.",
  "Transform the following {} passage into {}.",
  "Translate the {} words provided into {}.",
  "As an assistant skilled in both {} and {}, please translate the following text.",
  "Please translate the provided {} content into the {} language.",
  "Your task as an AI assistant is to translate this {} text into {}.",
  "Convert the text from {} to {}.",
  "As an AI fluent in {} and {}, please translate the text.",
  "Translate the given {} sentences into the {} language.",
  "You are an AI that understands {} and {}. Translate the following text.",
  "Please transform the {} text provided into {}.",
  "As an expert in {} and {}, your task is to translate the following.",
  "You are to translate the provided {} content into {}.",
  "As an AI translator, convert the given {} text into {}.",
  "Translate the text from {} into {}.",
  "You are a translation assistant, and your task is to translate this {} text into {}.",
  "Convert the {} content provided into the {} language.",
  "Translate the {} text below into {}.",
  "As a skilled translator, please render the following {} content into {}.",
  "Please translate the {} words below into {}.",
  "You are an AI skilled in {} and {}. Translate the following text.",
  "Your task is to convert the provided {} text into {}.",
  "Translate the given {} content into the {} language.",
  "As a proficient language assistant, translate the {} passage into {}.",
  "Translate the {} material provided into {}.",
  "You are an assistant trained in translation. Translate this {} text into {}.",
  "Convert the text from {} into {}.",
  "As an expert in translation, please transform the following {} text into {}.",
  "You are an AI trained in multiple languages. Translate the {} text into {}.",
  "Perform a translation of the provided {} text into {}.",
  "As an AI assistant, your task is to translate the following {} passage into {}.",
  "Take the {} sentences below and translate them into {}.",
  "You are a language expert. Please translate the given {} text into {}.",
  "Translate the text below from {} into the {} language.",
  "You have been tasked with translating this {} passage into {}. Please proceed.",
  "Render the following {} content into {}.",
  "As an AI with translation capabilities, convert the provided {} text into {}.",
  "Your assignment is to translate the {} text below into {}.",
  "As a translation assistant, your job is to convert the following {} text into {}.",
  "Translate the {} material provided into {}.",
  "You are skilled in {}. Translate the following {} content into that language.",
  "Convert the {} passage below into {}.",
  "As a language translation expert, please render the {} text into {}.",
  "Translate the text you see below from {} to {}.",
  "As an AI assistant fluent in {}, translate the provided {} text.",
  "Please change the following {} content into {}.",
  "Your role as a translator is to convert the {} text into {}.",
  "You are a skilled translator. Translate the following {} passage into {}.",
  "As a multilingual AI, your task is to translate the text from {} to {}.",
  "Translate the {} phrases provided into the {} language.",
  "You have been given {} text. Translate it into {}.",
  "Please translate the {} content below into {}.",
  "As a language specialist, render the following {} text into {}.",
  "Your task is to translate the {} sentences below into {}.",
  "As an AI skilled in language translation, convert the {} text into {}.",
  "Translate the {} words you see below into {}.",
  "You are a translator. Please convert the following {} text into {}.",
  "Perform the translation of the provided {} content into {}.",
  "As an assistant with translation skills, please change the {} passage into {}.",
  "Translate the text from {} to {} as requested.",
  "You are an AI language expert. Translate this {} text into {}.",
  "Please perform a translation of the {} text into {}.",
  "As a proficient translator, convert the following {} content into {}."
]

PREFIX_LIST_HEADLINE = [
  "Compose a headline for the following news article.",
  "You are an assistant tasked with creating a headline for the given news article.",
  "Create a concise and engaging headline for the news article below.",
  "As a copywriting expert, please write a headline for the following article.",
  "Summarize the following news article with a succinct headline.",
  "Your task is to write a headline for the provided news article.",
  "As an AI trained in journalism, craft a headline for the given article.",
  "Please create a compelling headline for the news story below.",
  "Write a headline for the following article that captures its essence.",
  "You are a headline writer. Create a headline for the provided news article.",
  "As an assistant skilled in summarizing, craft a headline for the news article below.",
  "Please develop a headline for the following news story.",
  "Your task as a news editor is to write a headline for the provided article.",
  "Create an engaging headline for the news article provided.",
  "You are an AI trained in media and journalism. Write a headline for the following news article.",
  "Summarize the article below with an attention-grabbing headline.",
  "Your role is to create a headline for the given news article.",
  "As a skilled content creator, please write a headline for the following news article.",
  "Craft a headline for the news story below that encapsulates its main theme.",
  "You are an assistant skilled in news summarization. Write a headline for the article below.",
  "Please create a concise headline for the following news article.",
  "As a headline specialist, your task is to write a headline for the provided news story.",
  "Write a headline that summarizes the main point of the following article.",
  "You have been given a news article. Create a headline that captures its essence.",
  "Please write a compelling headline for the news article provided.",
  "Your job as a news assistant is to craft a headline for the following article.",
  "Create a headline for the news article below that conveys its key message.",
  "You are a media expert. Please write a headline for the following news story.",
  "Your task is to summarize the provided news article with a fitting headline.",
  "Write a headline for the following news article that attracts readers' attention.",
  "As a content expert, craft a headline for the news story below.",
  "Create a headline for the following article that reflects its main theme.",
  "You are an assistant trained in journalism. Write a headline for the provided news article.",
  "Please develop a captivating headline for the news story below.",
  "As a professional headline writer, craft a headline for the following news article.",
    "Devise a headline for the following news article that encapsulates its core message.",
  "You are a headline creator. Please craft a headline for the news article below.",
  "Compose a brief and compelling headline for the provided news story.",
  "As a news editing assistant, write a headline for the given article.",
  "Sum up the following news article with a concise headline.",
  "Your responsibility is to create a headline for the provided news article.",
  "As an AI experienced in media writing, create a headline for the given news story.",
  "Please formulate a headline for the news article that conveys its main idea.",
  "Write a striking headline for the following news article.",
  "You are tasked with creating a headline for the provided news story.",
  "As a journalistic assistant, please craft a headline for the news article below.",
  "Create a succinct headline that reflects the content of the following news story.",
  "Your role as a media specialist is to write a headline for the given article.",
  "Generate a headline for the news article below that summarizes its key points.",
  "You are an AI trained in headline creation. Write a headline for the following news article.",
  "Create a headline for the following news story that will engage readers.",
  "Your task is to write a headline for the news article below that highlights its main focus.",
  "As an expert in news summarization, craft a headline for the given article.",
  "Compose a headline for the following news article that captures the reader's attention.",
  "You are a content creation assistant. Create a headline for the provided news story.",
  "Please write a headline for the news article that reflects its central theme.",
  "As a headline crafting expert, your task is to write a headline for the following news story.",
  "Write a headline that best summarizes the following article.",
  "You've been given a news article. Create a headline that represents its content.",
  "Please write an engaging headline for the provided news story.",
  "Your job as a content creator is to craft a headline for the following news article.",
  "Formulate a headline for the news story below that conveys its essence.",
  "You are a media creation expert. Please write a headline for the following news article.",
  "Your assignment is to create a headline for the provided news story that encapsulates its main idea.",
  "Write an attention-grabbing headline for the following news article.",
  "As a news writing specialist, craft a fitting headline for the article below.",
  "Create a headline for the following news story that summarizes its content.",
  "You are a journalistic AI. Write a headline for the provided news article.",
  "Please craft a compelling headline for the news article below.",
  "As a professional in news media, write a headline for the following news story."
]

PREFIX_LIST_SUMMARY = [
  "Summarize the following text in a concise and clear manner.",
  "You are an assistant tasked with providing a short summary of the given text.",
  "Write a brief summary that captures the essence of the text below.",
  "As a summarization expert, please condense the following text into a short summary.",
  "Your task is to create a succinct summary of the provided text.",
  "You are an AI trained in summarization. Write a short summary of the given text.",
  "Please provide a concise summary of the text that conveys its main points.",
  "Summarize the following content in a few sentences.",
  "You are a summarization assistant. Craft a brief summary for the text below.",
  "As an AI skilled in condensing information, provide a short summary of the following text.",
  "Write a short summary that encapsulates the main ideas of the text below.",
  "Your responsibility is to summarize the provided text in a brief and clear way.",
  "Create a brief summary for the following text that conveys its central theme.",
  "You are a content summarization expert. Summarize the text below.",
  "Please write a short summary that captures the key points of the following text.",
  "Your task as a summary writer is to condense the given text into a concise summary.",
  "Condense the following content into a short and meaningful summary.",
  "You are an AI skilled in content reduction. Write a brief summary of the text below.",
  "Please craft a short summary for the following text that highlights its main focus.",
  "You are tasked with writing a concise summary of the provided content.",
  "As a professional in summarization, create a short summary of the following text.",
  "Summarize the text below in a way that retains its key message.",
  "Your role is to provide a succinct summary of the given text.",
  "As a summary specialist, please condense the following text into a brief summary.",
  "Write a short summary of the following text that reflects its core idea.",
  "You are an assistant trained in summarization. Condense the text below into a brief summary.",
  "Please write a concise summary for the following text that conveys its essence.",
  "Your job as a content summarizer is to write a short summary of the provided text.",
  "Create a brief summary for the following text that captures its main insights.",
  "You are an expert in information condensation. Summarize the following text briefly.",
  "As a summarization assistant, craft a concise summary for the text below.",
  "Provide a short summary of the following text that highlights its main points.",
  "You are an AI skilled in brief summarization. Write a summary for the given text.",
  "Please create a short and meaningful summary for the following content.",
  "As a professional in content reduction, write a brief summary of the text below.",
  "Craft a concise summary of the text below that captures its key concepts.",
  "You are a summarization assistant. Please provide a brief summary of the given text.",
  "Write a short summary that encapsulates the essence of the following text.",
  "As an AI trained in summarizing information, condense the text below into a short summary.",
  "Your task is to write a succinct summary of the provided content.",
  "You are an expert in text summarization. Write a brief summary of the following text.",
  "Please offer a concise summary that conveys the main ideas of the text below.",
  "Summarize the following passage in a few meaningful sentences.",
  "You are tasked with creating a brief summary for the text provided.",
  "As a specialist in summarization, please write a short summary of the following text.",
  "Condense the content below into a short and impactful summary.",
  "Your role is to summarize the given text in a clear and concise manner.",
  "Create a succinct summary of the following text that reflects its core theme.",
  "You are a professional summarizer. Please write a short summary of the text below.",
  "Craft a brief summary for the following content that highlights its key points.",
  "Your task as a summary creator is to write a concise summary of the given text.",
  "Please provide a short summary that encapsulates the main message of the following text.",
  "You are an AI skilled in distilling information. Write a brief summary of the content below.",
  "Write a short summary of the following text that conveys its main insights.",
  "You are tasked with providing a concise summary of the text provided.",
  "As an expert in content summarization, create a brief summary for the following text.",
  "Summarize the text below, retaining its essential message in a short summary.",
  "Your responsibility is to craft a succinct summary of the text given.",
  "As a content reduction specialist, please condense the following text into a brief summary.",
  "Create a short summary of the following text that captures its main ideas.",
  "You are an assistant trained in content summarization. Write a brief summary for the text below.",
  "Please write a meaningful summary for the following text, keeping it concise.",
  "Your job as a summarization expert is to craft a short summary of the provided content.",
  "Formulate a brief summary for the following text that reflects its key insights.",
  "You are skilled in information synthesis. Please summarize the following text briefly.",
  "As a professional summary writer, craft a concise summary for the text below.",
  "Provide a short and engaging summary of the following content.",
  "You are an AI trained in brief summarization techniques. Summarize the text below.",
  "Please write a concise and insightful summary for the following passage.",
  "As a professional in text reduction, write a short summary for the text provided."
]

PREFIX_LIST_STORY_FROM_SUMMARY = [
  "Based on the following summary, write a short story that expands on the idea.",
  "You are an assistant trained in creative writing. Craft a short article based on the given idea.",
  "Take the provided summary and develop it into a compelling short story.",
  "As a storytelling expert, write a short article that expands on the following idea.",
  "Your task is to create a short story based on the brief summary provided.",
  "You are an AI skilled in content creation. Write a short article inspired by the given summary.",
  "Please write a short story that explores the concept described in the following summary.",
  "Create a short article that builds upon the idea presented in the given summary.",
  "You are a narrative assistant. Please write a short story based on the provided idea.",
  "As a professional writer, craft a short article that develops the following summary.",
  "Write a short story that creatively interprets the concept in the provided summary.",
  "Your responsibility is to create a short article inspired by the given idea.",
  "Develop the following summary into a captivating short story.",
  "You are an expert in creative writing. Write a short article based on the following idea.",
  "Craft a short story that delves into the theme described in the provided summary.",
  "Your task as a storyteller is to write a short article inspired by the given summary.",
  "Please write a short story that brings the provided idea to life.",
  "You are an AI skilled in narrative creation. Craft a short article based on the following summary.",
  "Create a short article that elaborates on the concept described in the provided idea.",
  "You are tasked with writing a short story inspired by the provided summary.",
  "As a creative writing specialist, develop the following idea into a short article.",
  "Write a short story that builds upon the theme presented in the given summary.",
  "Your role is to craft a short article that explores the idea described below.",
  "As a professional in content development, write a short story based on the following summary.",
  "Create a short story that encapsulates the essence of the idea provided.",
  "You are a writing assistant trained in storytelling. Write a short article inspired by the given idea.",
  "Please craft a short story that develops the concept described in the following summary.",
  "Your job as a creative writer is to write a short article based on the provided idea.",
  "Write a short article that elaborates on the theme described in the given summary.",
  "You are skilled in narrative construction. Please write a short story based on the following idea.",
  "As a storytelling expert, develop a short article that expands on the given summary.",
  "Create a captivating short story inspired by the concept presented below.",
  "You are an AI trained in creative content. Write a short article based on the provided summary.",
  "Please craft a short story that builds upon the idea described in the summary below.",
  "As a content creation professional, write a short article inspired by the following concept.",
  "Using the summary below, craft a short story that explores its themes.",
  "You are an assistant skilled in creative storytelling. Write an article based on the given idea.",
  "Take the provided concept and develop it into an engaging short story.",
  "As an expert in narrative writing, create a short article inspired by the following summary.",
  "Your task is to write a short story that delves into the idea provided below.",
  "You are a writing AI trained to expand ideas. Create an article based on the following summary.",
  "Please write a short story that captures the essence of the concept described in the summary.",
  "Compose a short article that elaborates on the theme presented in the given idea.",
  "You are a narrative craft assistant. Develop a short story based on the provided summary.",
  "As a professional in creative writing, weave a short article inspired by the following idea.",
  "Create a short story that brings to life the concept described in the provided summary.",
  "Your role is to write a short article that expands on the given idea.",
  "Develop the following theme into an intriguing short story.",
  "You are skilled in turning ideas into narratives. Write an article based on the following summary.",
  "Write a short story that creatively builds upon the idea described below.",
  "Your task as a creative writer is to compose an article inspired by the given summary.",
  "Please craft a short story that fully explores the concept in the provided idea.",
  "You are an AI specializing in storytelling. Write a short article based on the following theme.",
  "Create a short article that interprets the theme described in the given summary.",
  "You are assigned to write a short story inspired by the concept provided below.",
  "As a writer skilled in thematic development, create a short article from the following summary.",
  "Construct a short story that enhances the idea presented in the given summary.",
  "Your responsibility is to write a short article that illuminates the theme described below.",
  "As a content creation expert, fashion a short story based on the provided idea.",
  "Write a short story that resonates with the essence of the summary provided.",
  "You are an assistant trained in expanding concepts. Write an article inspired by the given summary.",
  "Please develop a short story that encapsulates the theme described in the following idea.",
  "Your mission as a writer is to create a short article based on the provided concept.",
  "Formulate a short article that investigates the theme outlined in the given summary.",
  "You are proficient in transforming summaries into narratives. Write a short story based on the idea below.",
  "As a creative content assistant, pen a short article inspired by the following summary.",
  "Compose a gripping short story inspired by the theme presented in the summary below.",
  "You are an AI capable of thematic exploration. Write an article based on the provided idea.",
  "Please weave a short story that draws from the concept described in the summary below.",
  "As a narrative professional, craft a short article that delves into the following concept."
]

PREFIX_LIST_STORY_FROM_HEADLINE = ["Using the headline below, write a short story that explores its subject matter.",
  "You are an assistant trained in journalism. Craft an article based on the given headline.",
  "Take the provided headline and develop it into an engaging short story.",
  "As a reporter, create a short article inspired by the following headline.",
  "Your task is to write a short story that delves into the theme provided in the headline.",
  "You are a writing AI skilled in news creation. Write an article based on the following headline.",
  "Please write a short story that captures the essence of the concept described in the headline.",
  "Compose a short article that expands on the topic presented in the given headline.",
  "You are a news writing assistant. Develop a short story based on the provided headline.",
  "As a professional journalist, write a short article inspired by the following headline.",
  "Create a short story that brings to life the subject described in the provided headline.",
  "Your role is to write a short article that explores the theme in the given headline.",
  "Develop the following headline into an intriguing short story.",
  "You are skilled in turning headlines into stories. Write an article based on the following headline.",
  "Write a short story that creatively builds upon the idea in the provided headline.",
  "Your task as a news writer is to compose an article inspired by the given headline.",
  "Please craft a short story that fully explores the concept in the provided headline.",
  "You are an AI specializing in journalistic writing. Write a short article based on the following headline.",
  "Create a short article that interprets the theme described in the given headline.",
  "You are assigned to write a short story inspired by the headline provided below.",
  "As a writer skilled in news reporting, create a short article from the following headline.",
  "Construct a short story that enhances the idea presented in the given headline.",
  "Your responsibility is to write a short article that illuminates the subject described in the headline.",
  "As a content creation expert, fashion a short story based on the provided headline.",
  "Write a short story that resonates with the theme of the headline provided.",
  "You are an assistant trained in article writing. Write an article inspired by the given headline.",
  "Please develop a short story that encapsulates the subject described in the following headline.",
  "Your mission as a writer is to create a short article based on the provided headline.",
  "Formulate a short article that investigates the subject outlined in the given headline.",
  "You are proficient in crafting narratives from headlines. Write a short story based on the headline below.",
  "As a journalistic assistant, pen a short article inspired by the following headline.",
  "Compose a gripping short story inspired by the theme presented in the headline below.",
  "You are an AI capable of news creation. Write an article based on the provided headline.",
  "Please weave a short story that draws from the subject described in the headline below.",
  "As a narrative professional, craft a short article that explores the theme in the following headline.",
  "Using the headline provided, create a short story that delves into the subject.",
  "You are an AI journalist. Write an article inspired by the headline below.",
  "Take the given headline and transform it into an engaging narrative in the form of a short story.",
  "As a seasoned writer, craft a short article that brings life to the following headline.",
  "Your task is to weave a short story inspired by the theme presented in the headline.",
  "You are a writing assistant skilled in news development. Compose an article from the provided headline.",
  "Please write a compelling short story that interprets the subject described in the headline.",
  "Write a short article that enriches the topic conveyed in the given headline.",
  "You are a narrative construction AI. Write a short story that expands on the provided headline.",
  "As a professional content creator, write a short article that delves into the headline below.",
  "Create a short story that explores the complex themes hinted at in the provided headline.",
  "Your role as a creative writer is to draft an article that unfolds the idea in the given headline.",
  "Turn the headline below into a captivating short story filled with insights and details.",
  "You are specialized in transforming headlines into engaging narratives. Write an article based on the headline.",
  "Write a short story that brings depth and perspective to the provided headline.",
  "Your assignment as a news writer is to create an informative article based on the given headline.",
  "Please draft a short story that paints a vivid picture of the concept in the provided headline.",
  "You are an AI trained for editorial writing. Craft an article inspired by the following headline.",
  "Create an insightful short article that reflects the theme depicted in the given headline.",
  "You are tasked with developing a short story that embodies the essence of the provided headline.",
  "As a creative journalist, weave an article that resonates with the subject of the following headline.",
  "Build a narrative in the form of a short story that enhances the idea in the given headline.",
  "Your mission is to write a short article that delves into the intrigue described in the headline.",
  "As a storytelling expert, create a fascinating short story based on the provided headline.",
  "Write a short story that provides a unique perspective on the theme of the headline provided.",
  "You are a digital assistant focused on narrative expansion. Write an article from the given headline.",
  "Please craft a short story that explores the multifaceted theme described in the following headline.",
  "Your role as an article writer is to generate a piece that embodies the concept in the provided headline.",
  "Form a short article that unravels the complexity of the subject outlined in the given headline.",
  "You excel in narrative creation from brief ideas. Write a short story based on the headline below.",
  "As a creative assistant, draft an engaging article that reflects the theme in the following headline.",
  "Compose an imaginative short story that draws inspiration from the theme presented in the headline below.",
  "You are an AI with expertise in news storytelling. Write an in-depth article based on the provided headline.",
  "Please create a short story that builds a world around the subject described in the headline below.",
  "As a professional in narrative crafting, shape a short article that explores the nuance of the following headline."
]